var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var h=a[e];h in c||(c[h]={});c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,h=0;h<e;h++){var m=a[h];if(b.call(c,m,h,a))return{i:h,v:m}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");$jscomp.polyfill("Math.log10",function(a){return a?a:function(a){return Math.log(a)/Math.LN10}},"es6-impl","es3");
function resetEngineStates(){window.gameId=-1;window.stopLinesAnimation=!1;window.stopAutoplay=!1;window.autoplay=!1;window.needCollect=!1;window.reelsRunned=!1;window.inGambleState=!1;window.inGambleAnimation=!1;window.symbolWidth=window.currentSymbolWidth||222;window.symbolHeight=window.currentSymbolHeight||222;window.renderers=[];window.stages=[];window.preset=null;window.symbolsImages2=[];window.symbolsTopMenu=[];window.reelsRunned=!1;window.reelsDist=[];window.reels=!1;window.pSpecIndex=[];window.needExit=
!1;window.gameComplete=!1;window.pIndex=_.map(_.range(window.gameConfig.getMatrixIndeces()[0].length),function(){return 0});window.reels=_.map(_.range(window.gameConfig.getMatrixIndeces()[0].length),function(){return[]});window.newspin=!1;window.spintoken=!1;window.specGame=!1;window.specGamesCount=0}function hideLobby(){$("#lobby").hide();$("#game").show();applyScale()}function showLobby(){$("#game").hide();$("#preloader-background").show();$("#lobby").show();applyScale();showUserBalance()}
function unloadGame(){window.currentSymbolWidth=!1;window.currentSymbolHeight=!1;window.data=!1;window.newspin=!1;window.spintoken=!1;hideGamble();$("#reels-outer").empty();$("#button-start").removeClass("button-skip").text("Start");$("#button-autoplay").text("Autoplay");_.each(window.renderers,function(a){a.destroy()});resetEngineStates();unloadOldScripts();document.title="Lobby";showLobby()}
function unloadOldScripts(){var a=!1;_.each($("script"),function(b){b=$(b);b.attr("src")&&("game-specific"==b.attr("data-tag")&&-1==b.attr("src").indexOf("engine.js")&&b.remove(),-1!=b.attr("src").indexOf("scripts/config.js")&&b.remove(),-1!=b.attr("src").indexOf("engine.js")&&(a=b))});_.each($("link"),function(a){a=$(a);"game-specific"==a.attr("data-tag")&&a.remove()});_.each($("body > div"),function(a){a=$(a);"game-specific"==a.attr("data-tag")&&a.remove()});return a}
function loadGame(a){var b=unloadOldScripts(),c=$(document.createElement("script")).attr("type","text/javascript").attr("src","../games/"+a+"/scripts/config.js");b.after(c);_.each(window.gameConfig.preloaderSettings.scripts,function(c){c=$(document.createElement("script")).attr("type","text/javascript").attr("src",c[1]?"../common/scripts/"+c[0]+".js":"../games/"+a+"/scripts/"+c[0]+".js").attr("data-tag","game-specific");b.before(c)});var e=!1;_.each($("link"),function(a){a=$(a);-1!=a.attr("href").indexOf("/common/")&&
(e=a)});_.each(window.gameConfig.preloaderSettings.styles,function(b){b=$(document.createElement("link")).attr("rel","stylesheet").attr("text","text/css").attr("href",b[1]?"../common/styles/"+b[0]+".css":"../games/"+a+"/styles/"+b[0]+".css").attr("data-tag","game-specific");e.before(b)});_.each(window.gameConfig.preloaderSettings.blocks,function(b){$.ajax({type:"GET",url:b[1]?"../common/php/"+b[0]+".php":"../games/"+a+"/"+b[0]+".php",async:!1,success:function(a){$(a).appendTo("body").attr("data-tag",
"game-specific")}})});resetEngineStates();hideLobby();showUserBalance();document.title=window.gameConfig.preloaderSettings.name;c=new XMLHttpRequest;c.open("GET","/common/php/getidbypath.php?path="+a,!1);c.send();200==c.status&&(window.gameId=parseInt(c.responseText));preloader(window.gameConfig.preloaderSettings,function(a){window.data=a;window.gameConfig.postloader&&window.gameConfig.postloader();if(window.gameConfig.manualAnimationLength){a=window.gameConfig.manualAnimationLength;for(var b in window.data["animations-length"])-1!=
_.keys(window.data.symbols).indexOf(b+"_l")&&1==window.data["animations-length"][b]&&(window.data["animations-length"][b]=a)}genReels(window.gameConfig.getMatrixIndeces()[0].length);for(b=0;b<$(".reel").length;++b){var c=$("#reel-"+b);a=!1;a=isiOS()?new PIXI.WebGLRenderer(window.symbolWidth,3*window.symbolHeight,{transparent:!0}):PIXI.autoDetectRenderer(window.symbolWidth,3*window.symbolHeight,{transparent:!0});a instanceof PIXI.WebGLRenderer||(a.context.mozImageSmoothingEnabled=!1,a.context.webkitImageSmoothingEnabled=
!1);a.view.style.transform="translatez(0)";c.append(a.view);window.renderers.push(a);c=new PIXI.Container;window.stages.push(c);window.renderers[b].render(window.stages[b])}b=new XMLHttpRequest;b.open("GET","/common/php/getpreset.php?gameid="+window.gameId,!1);b.send();200==b.status?(b=JSON.parse(b.responseText).preset,window.preset=_.map(b.split("|"),function(a){return _.map(a.split(","),function(a){return a.replace(/\'/g,"").trim()})}),window.presetSymbols=generatePresetSymbols(_.keys(_.groupBy(_.flatten(window.preset),
function(a){return a[0]})))):alert("error");b=new XMLHttpRequest;b.open("GET","/common/php/getnewspin.php?gameid="+window.gameId,!1);b.send();if(200==b.status)for(a=JSON.parse(b.responseText),window.reelsDist=Array($(".reel").length),b=0;b<a.spin.length;++b)pIndex[b]=a.spin[b],pIndex[b]>=window.preset[b].length&&(pIndex[b]%=window.preset[b].length);for(b=0;b<$(".reel").length;++b){a=window.renderers[b];for(var c=window.stages[b],e=0;3>e;++e){var k=getNextSymbol(b),g=data["pixi-symbols"][window.gameConfig.symbols[k]],
d=new PIXI.Sprite(g),g=new PIXI.Sprite(g);window.reels[b].push({x:0,y:e*window.symbolHeight,obj:d,objSmooth:g,symbol:window.gameConfig.symbols[k]});d.position.x=0;d.position.y=e*window.symbolHeight;c.addChild(d)}a.render(c)}$(document).nodoubletapzoom();$("body").nodoubletapzoom();$("#mobile-rotate-background").nodoubletapzoom();$("#body-repeat").nodoubletapzoom();$("#button-autoplay").nodoubletapzoom();$("#button-paytable").nodoubletapzoom();$("#button-gamble").nodoubletapzoom();$("#button-start").nodoubletapzoom();
$(".b-plus").nodoubletapzoom();$("#top-menu-center").nodoubletapzoom();$("#reels-outer").nodoubletapzoom();$("#reel-fore-outer").nodoubletapzoom();$("#paytable-outer").nodoubletapzoom();$("#gamble-outer").nodoubletapzoom();$("#footer-outer").nodoubletapzoom();applyScale();initButtons();createIndicators();rewriteStaticMatrix();setNewSpin(function(){})})}
function genReels(a){for(var b=0;b<a;++b){var c=$(document.createElement("div")).addClass("reel").attr("id","reel-"+b);$("#reels-outer").append(c)}}
function getNextSymbolDefault(a,b){if(!window.preset)if(0<=window.gameId){var c=new XMLHttpRequest;b?c.open("GET","/common/php/getpreset.php?gameid="+window.gameId+"&presetid="+b,!1):c.open("GET","/common/php/getpreset.php?gameid="+window.gameId,!1);c.send();200==c.status?(c=JSON.parse(c.responseText),b=c.presetid,window.preset=_.map(c.preset.split("|"),function(a){return _.map(a.split(","),function(a){return a.replace(/\'/g,"").trim()})}),window.presetSymbols=generatePresetSymbols(_.keys(_.groupBy(_.flatten(window.preset),
function(a){return a[0]})))):alert("error")}else alert("error");var c=pIndex[a],e=window.presetSymbols[window.preset[a][c]];++c;c>=window.preset[a].length&&(c%=window.preset[a].length);pIndex[a]=c;return e}function getNextSymbol(a,b){return window.specGame&&!window.preset?getNextSymbolDefault(a,"bonus"):getNextSymbolDefault(a)}function play(a,b){return window.gameConfig.play?window.gameConfig.play(a,b):playDefault(a,b)}
function playDefault(a,b){window.needExit||(window.gameComplete=!1,$(".symbol-video").remove(),window.stopLinesAnimation=!0,stopSoundById("cash-sound"),a&&a(),runReels(function(){b&&b()}))}
function showAllLines(){var a=document.getElementById("reel-fore");$(a).attr("width",$(a).css("width"));$(a).attr("height",$(a).css("height"));var b=a.getContext("2d");b.save();b.translate(12,0);var c=getMatrixLines(),e=0;_.each(c,function(c){var m=parseInt($("#linesCountField").text());if(!(e+1>m)){var m=$("#line-"+(e+1)+"-indicator-left").offset().top-$(a).offset().top+$("#line-"+(e+1)+"-indicator-left").height()/2,l=$("#line-"+(e+1)+"-indicator-right").offset().top-$(a).offset().top+$("#line-"+
(e+1)+"-indicator-right").height()/2;b.strokeStyle=0>e?"#ffd700":$("#line-"+(e+1)+"-indicator-left").css("background-color");b.lineWidth=8;b.beginPath();b.moveTo(-5,m);for(var n=$(a).width()/$(".reel").length,k=!1,g=0,d=0;d<c.length;++d)d?d==c.length-1?b.lineTo(n*d+n/2,l):(Math.floor(k)!=Math.floor(c[d].y)&&(g+=Math.floor(c[d].y)-Math.floor(k),k=Math.floor(c[d].y)),b.lineTo(n*d+n/2,m+g)):(b.lineTo(n*d+n/2,m),k=Math.floor(c[d].y));b.lineTo($("#line-"+(e+1)+"-indicator-right").offset().left-$("#line-"+
(e+1)+"-indicator-left").offset().left-$("#line-"+(e+1)+"-indicator-left").width(),l);b.stroke();++e}});b.restore()}
function createIndicators(){var a=0;_.each(window.gameConfig.indicators,function(b){_.each(b,function(b){b=$(document.createElement("div")).addClass("line-indicator").attr("id","line-"+b.id+"-indicator-"+(a?"right":"left")).css("position","absolute").css("margin-left",b.left).css("margin-top",b.top).css("background-color",b.color).css("box-shadow","0px 0px 13px 7px #000000").text(b.id);$("#reels-outer").prepend(b)});++a})}
function createWinBorders(a,b,c,e){if(!window.gameComplete){var h=document.getElementById("reel-fore");$(h).attr("width",$(h).css("width"));$(h).attr("height",$(h).css("height"));var m=h.getContext("2d");m.save();m.translate(12,0);m.strokeStyle=0>c?"#ffd700":$("#line-"+(c+1)+"-indicator-left").css("background-color");m.lineWidth=8;if(0<=c){var l=$("#line-"+(c+1)+"-indicator-left").offset().top-$(h).offset().top+$("#line-"+(c+1)+"-indicator-left").height()/2,n=$("#line-"+(c+1)+"-indicator-right").offset().top-
$(h).offset().top+$("#line-"+(c+1)+"-indicator-right").height()/2;m.beginPath();m.moveTo(-5,l);for(var k=$(h).width()/$(".reel").length,g=!1,d=0,p=0;p<a.length;++p)p?p==a.length-1?m.lineTo(k*p+k/2,n):(Math.floor(g)!=Math.floor(a[p].y)&&(d+=Math.floor(a[p].y)-Math.floor(g),g=Math.floor(a[p].y)),m.lineTo(k*p+k/2,l+d)):(m.lineTo(k*p+k/2,l),g=Math.floor(a[p].y));m.lineTo($("#line-"+(c+1)+"-indicator-right").offset().left-$("#line-"+(c+1)+"-indicator-left").offset().left-$("#line-"+(c+1)+"-indicator-left").width(),
n);m.stroke()}for(p=0;p<b.length;++p)l=b[p],l.css("display","block"),m.clearRect($("#reel-"+l.attr("data-left")).offset().left-$(h).offset().left-12,$("#reel-"+l.attr("data-left")).offset().top+parseInt(l.attr("data-top"))-$(h).offset().top,window.symbolWidth,window.symbolHeight),$("#reel-"+l.attr("data-left")).append(l),l.attr("data-playsound")&&playSoundById(l.attr("data-playsound")),function(a){a.addEventListener("load",function(){a=$(a);if(!0!==e)for(var b=0;b<$(".reel").length;++b)if(parseInt(a.attr("data-left"))==
b&&reels[b].length&&_.first(reels[b]).y<=3*window.symbolHeight){for(var c=window.renderers[b],d=window.stages[b],l=d.children.length-1;0<=l;--l)d.removeChild(d.children[l]);for(var l=reels[b],h=parseInt(a.attr("data-top")),k=0;k<l.length;++k){var g=l[k];if(!1!==g&&!(g.y>=h-10&&g.y<=h+10)){var m=g.obj;m.position.x=g.x||"undefined"!=typeof e&&g.reel;m.position.y=g.y;d.addChild(m)}}c.render(d)}},!1)}(l[0]),m.strokeRect($("#reel-"+l.attr("data-left")).offset().left-$(h).offset().left-12,$("#reel-"+l.attr("data-left")).offset().top+
parseInt(l.attr("data-top"))-$(h).offset().top,window.symbolWidth,window.symbolHeight),m.strokeRect($("#reel-"+l.attr("data-left")).offset().left-$(h).offset().left-12,$("#reel-"+l.attr("data-left")).offset().top+parseInt(l.attr("data-top"))-$(h).offset().top,window.symbolWidth,window.symbolHeight),p||(n=""+(getLineWin(a)+getScattersWin(getScatters())),m.lineWidth=8,m.font="bold 26px Arial",k=m.measureText(n),m.fillStyle="black",m.fillRect(l.offset().left-$(h).offset().left-12+30-3,l.offset().top-
$(h).offset().top-15+3,k.width+18,38),m.strokeRect(l.offset().left-$(h).offset().left-12+30-3,l.offset().top-$(h).offset().top-15+3,k.width+18,38),m.fillStyle=0>c?"#ffd700":$("#line-"+(c+1)+"-indicator-left").css("background-color"),m.fillText(n,l.offset().left-$(h).offset().left-12+36,l.offset().top-$(h).offset().top+16));m.restore()}}
function removeAllWinBorders(){$(".symbol-video").remove();var a=document.getElementById("reel-fore");$(a).attr("width",$(a).css("width"));$(a).attr("height",$(a).css("height"));var b=a.getContext("2d");b.save();b.translate(12,0);b.clearRect(-100,-100,a.width,a.height);b.restore()}
function rewriteStaticMatrix(){for(var a=0;a<$(".reel").length;++a)if(reels[a].length&&_.first(reels[a]),reels[a].length&&_.first(reels[a]).y<=3*window.symbolHeight){for(var b=window.renderers[a],c=window.stages[a],e=c.children.length-1;0<=e;--e)c.removeChild(c.children[e]);for(var e=reels[a],h=0;h<e.length;++h){var m=e[h],l=m.obj;l.position.x=m.x;l.position.y=m.y;c.addChild(l)}b.render(c)}}
function calcLineDisplayTimeDefault(a){for(var b=1E3,c=0;c<a.length;++c){var e=100*window.data[5<=a.length?"animations-red-length":"animations-length"][a[c]];e>b&&(b=e)}return b}function calcLineDisplayTime(a){return window.gameConfig.calcLineDisplayTime?window.gameConfig.calcLineDisplayTime(a):calcLineDisplayTimeDefault(a)}
function gameOverDefault(a){window.stopLinesAnimation=!1;var b=getMatrixLines(),c=[];console.log("============ game complete ============");for(var e=0,h=0,m=[],l=0;l<b.length;++l){var n=getMatrixLineFruit(b[l]);n&&window.gameConfig.fruitsFilter&&(n=window.gameConfig.fruitsFilter(n));if(n){for(var k=[],g=0;g<n.length;++g){var d=createFireVideo(_.map(n,function(a){return a.symbol}),n[g].symbol,n.length).attr("data-left",g).attr("data-top",n[g].y).attr("data-symbol",n[g].symbol).css("top",n[g].y);k.push(d)}(g=
getLineWin(n))&&c.push([b[l],k,l]);g&&(++h,e+=g,console.log("line "+(l+1)+": ["+_.map(n,function(a){return a.symbol}).join(", ")+"] = "+g),m.push(_.map(n,function(a){return a.symbol}).join(",")+"="+g))}}console.log("win lines count: "+h);k=0;if(b=getScatters()){k=[];for(g=0;g<b.length;++g)d=createFireVideo(_.map(b,function(a){return a.symbol}),b[g].symbol,b.length).attr("data-left",b[g].xpos).attr("data-top",b[g].y).attr("data-symbol",b[g].symbol).css("top",b[g].y),k.push(d);c.push([!1,k,-1]);k=getScattersWin(b);
console.log("scatters: ["+_.map(b,function(a){return a.symbol}).join(", ")+"] = "+k);m.push(_.map(b,function(a){return a.symbol}).join(",")+"="+k)}e+=k;console.log("total win: "+e);window.gameId&&(m={spin:m.join("|"),win:e,gameid:window.gameId,id:window.newspin,token:window.spintoken,bet:parseInt($("#betLineField").text()),betlines:parseInt($("#linesCountField").text()),matrix:_.map(getMatrix(),function(a){return _.map(a,function(a){return a.symbol}).join(",")}).join("|"),balance:parseInt($("#creditField").text())+
e},$.post("/common/php/logspin.php",m),console.log(m),window.newspin=!1,window.spintoken=!1);console.log("=======================================");var p=-1,f=function(b){if(window.autoplay&&(b||++p,1<=p)){a&&a();return}for(var d=0;d<c.length;++d)if(d!=b)for(var l=c[d][1],e=0;e<l.length;++e)l[e].css("display","none");createWinBorders(c[b][0],c[b][1],c[b][2]);var d=b>=c.length-1?0:b+1,g=calcLineDisplayTime(_.map(c[b][1],function(a){return a.attr("data-symbol")}));window.stopLinesAnimation?(b=document.getElementById("reel-fore"),
$(b).attr("width",$(b).css("width")),$(b).attr("height",$(b).css("height")),b.getContext("2d").clearRect(0,0,$(b).width(),$(b).height()),rewriteStaticMatrix(),a&&a()):function(a){setTimeout(function(){rewriteStaticMatrix();window.stopLinesAnimation||(window.requestAnimationFrame?function(a){requestAnimationFrame(function(){f(a)})}(a):f(a))},g)}(d)};c.length?(isSoundEnabled()&&playSoundById("cash-sound"),f(0),window.needCollect=!0,$("#button-start").text("Collect"),window.totalWin=calculateWin(),$("#lastWinField").text(window.totalWin)):
a&&a()}function gameOver(a){window.gameConfig.gameOver?window.gameConfig.gameOver(a):gameOverDefault(a)}
function transferWin(a){var b=window.totalWin;window.needCollect=!1;window.totalWin=0;var c=parseInt($("#creditField").text());stopSoundById("cash-sound");0<b&&playSoundById("credit-increase");var e=function(){10<b?(step=1E5<b?Math.floor(b/10):1E4<b?1E4:1E3<b?1E3:100<b?100:10<b?10:1,b-=step,c+=step,$("#creditField").text(c),setLabelInfo(b+"  won"),setTimeout(e,75)):(c+=b,b=0,$("#creditField").text(c),setLabelInfo(b+"  won"),stopSoundById("credit-increase"),rewriteStaticMatrix(),updateBalance($("#creditField").text()),
a&&a())};e()}
function correctPayTable(){var a=window.gameConfig.getWinMatrix();_.each(_.keys(a),function(b){_.each(_.range(window.gameConfig.getMatrixIndeces().length+1),function(c){var e=a[b][c]*(window.gameConfig.isScatter(b)?parseInt($("#betField").text()):parseInt($("#betLineField").text()));$("#paytable-"+b+"-"+c).text(e)})});_.each(window.gameConfig.preloaderSettings.symbols,function(a){var c=$(window.data.symbols[a]).clone().css("width","50px").css("height","50px");$("#paytable-icon-"+a).css("float","left").css("width",
"50px").css("margin","3px").append(c)})}function getLineWin(a){if(!a)return 0;for(var b=parseInt($("#betLineField").text()),c=window.gameConfig.isSubstitute(a[0].symbol)?!1:a[0].symbol,e=1,h=1;h<a.length;++h)if(c)if(window.gameConfig.isSubstitute(a[h].symbol))++e;else if(c==a[h].symbol)++e;else break;else window.gameConfig.isSubstitute(a[h].symbol)?++e:(++e,c=a[h].symbol);return(a=c?window.gameConfig.getWinMatrix()[c][e]:0)?a*b:0}
function getScattersWin(a){var b=parseInt($("#betField").text());return a.length?window.gameConfig.getWinMatrix()[a[0].symbol][a.length]*b:0}function calculateWin(){for(var a=getMatrixLines(),b=0,c=0;c<a.length;++c)b+=getLineWin(a[c]);getScatters();parseInt($("#betLineField").text());b+=getScattersWin(getScatters());setLabelInfo(b+"  won");return b}function setLabelInfo(a){$("#label-info").find("span").text(a)}
function createFireVideoDefault(a,b,c){a=c==window.gameConfig.getMatrixIndeces()[0].length&&data["animations-red"][b]?data["animations-red"][b]:data.animations[b];c=$(a).clone();(function(a){a[0].addEventListener("load",function(){a.attr("data-loaded","true")},!1)})(c);c.css("width",window.symbolWidth+"px").css("height",(a.height>=window.symbolHeight?a.height:window.symbolHeight)+"px").addClass("symbol-video").attr("data-symbol",b);return c}
function createFireVideo(a,b,c){return window.gameConfig.createFireVideo?window.gameConfig.createFireVideo(a,b,c):createFireVideoDefault(a,b,c)}function runReels(a){if(!window.newspin){for(var b=0;b<window.reelsDist.length;++b)window.reelsDist[b]=1E3;setNewSpin(function(){})}(function(a){return window.gameConfig.runReels?window.gameConfig.runReels(a):runReelsDefault(a)})(a)}
function runReelsDefault(a){if(!reelsRunned){removeAllWinBorders();rewriteStaticMatrix();var b=parseInt($("#betField").text()),c=parseInt($("#creditField").text());if(!(c<b)){window.specGame?$("#label-info > span").text("Bonus Games: "+window.specGamesCount):setLabelInfo("Good luck!");updateBalance(c-b);reelsRunned=!0;for(var e=[],b=0;b<$(".reel").length;++b)e.push(0);var h=(new Date).getTime(),m=function(b){var c=b-h,c=20>=c?20:c,c=Math.ceil(2.5*(25<c?25:c));h=b;for(b=0;b<$(".reel").length;++b){$("#reel-"+
b);var k=_.first(reels[b]).y;if(k>=-window.symbolHeight){0<window.reelsDist[b]&&--window.reelsDist[b];var g=getNextSymbol(b);if(window.specSymbol&&window.specSymbol==window.gameConfig.symbols[g])var d=data["pixi-symbols"][window.specSymbol+"_f"],p=data["pixi-symbols"][window.specSymbol+"_fb"];else d=data["pixi-symbols"][window.gameConfig.symbols[g]],p=data["pixi-symbols"][window.gameConfig.symbols[g]+"_b"];var f=new PIXI.Sprite(d),d=new PIXI.Sprite(p);f.position.y=k-window.symbolHeight;d.position.y=
k-window.symbolHeight;reels[b].unshift({x:0,y:k-window.symbolHeight,obj:f,objSmooth:d,symbol:window.gameConfig.symbols[g]});window.stages[b].addChild(-3==window.reelsDist[b]?f:d)}if(!q&&reels[b].length)if(f=reels[b],0<window.reelsDist[b])for(d=0;d<f.length;++d)f[d].y+=c,f[d].obj.position.y+=c,f[d].objSmooth.position.y+=c,f[d].y>=3*window.symbolHeight&&(k=reels[b].pop(),window.stages[b].removeChild(k.obj),window.stages[b].removeChild(k.objSmooth));else if(!window.reelsDist[b]){for(d=0;d<f.length;++d)f[d].y+=
c,f[d].obj.position.y+=c,f[d].objSmooth.position.y+=c;playSoundById("reel-stop-sound-"+b);window.reelsDist[b]=-1;e[b]=1}else if(-1==window.reelsDist[b]){k=(3-(Math.log10(e[b])+2.3))/3;if(0<k)for(g=25*k,d=0;d<f.length;++d)f[d].y+=g,f[d].obj.position.y+=g,f[d].objSmooth.position.y+=g;if(0>=k){window.reelsDist[b]=-2;e[b]=1;k=.35*window.symbolHeigh;g=111;for(d=0;d<f.length;++d)f[d].y>=k-g&&f[d].y<=k+g?(f[d].y=k,f[d].obj.position.y=k,f[d].objSmooth.position.y=k):f[d].y>=window.symbolHeight+k-g&&f[d].y<=
window.symbolHeight+k+g?(f[d].y=window.symbolHeight+k,f[d].obj.position.y=window.symbolHeight+k,f[d].objSmooth.position.y=window.symbolHeight+k):f[d].y>=2*window.symbolHeight+k-g&&f[d].y<=2*window.symbolHeight+k+g&&(f[d].y=2*window.symbolHeight+k,f[d].obj.position.y=2*window.symbolHeight+k,f[d].objSmooth.position.y=2*window.symbolHeight+k);for(d=k=0;d<f.length;++d)if(f[d].y<3*window.symbolHeight)k=d;else break;g=f[k].y;for(d=k-1;0<=d;--d)g-=window.symbolHeight,f[d].y=g,f[d].obj.position.y=g,f[d].objSmooth.position.y=
g}else e[b]+=1.5}else if(-2==window.reelsDist[b]){k=3-(Math.log10(e[b])+2);if(0<k)for(g=25*k,d=0;d<f.length;++d)f[d].y-=g,f[d].obj.position.y-=g,f[d].objSmooth.position.y-=g;g=111;if(0>=k){window.reelsDist[b]=-3;for(d=0;d<f.length;++d)f[d].y>=-g&&f[d].y<=g?(f[d].y=0,f[d].obj.position.y=0,f[d].objSmooth.position.y=0):f[d].y>=window.symbolHeight-g&&f[d].y<=window.symbolHeight+g?(f[d].y=window.symbolHeight,f[d].obj.position.y=window.symbolHeight,f[d].objSmooth.position.y=window.symbolHeight):f[d].y>=
2*window.symbolHeight-g&&f[d].y<=2*window.symbolHeight+g&&(f[d].y=2*window.symbolHeight,f[d].obj.position.y=2*window.symbolHeight,f[d].objSmooth.position.y=2*window.symbolHeight);for(d=k=0;d<f.length;++d)if(f[d].y<3*window.symbolHeight)k=d;else break;g=f[k].y;for(d=k-1;0<=d;--d)g-=window.symbolHeight,f[d].y=g,f[d].obj.position.y=g,f[d].objSmooth.position.y=g}else e[b]+=1.5}if(!q&&reels[b].length&&_.first(reels[b]).y<=3*window.symbolHeight){q=window.renderers[b];k=window.stages[b];if(-3==window.reelsDist[b]){for(f=
k.children.length-1;0<=f;--f)k.removeChild(k.children[f]);g=reels[b];for(p=0;p<g.length;++p)d=g[p],f=-2>=window.reelsDist[b]?d.obj:d.objSmooth,f.position.x=d.x,f.position.y=d.y,k.addChild(f)}q.render(k)}for(var q=!0,f=0;f<window.reelsDist.length;++f)if(-3<window.reelsDist[f]){q=!1;break}}var r=function(){if(window.mobilePhonePaused)setTimeout(r,500);else return!1};q?r()||function(){rewriteStaticMatrix();reelsRunned=!1;stopSoundById("reel-run-sound");window.reelsRunned=!1;gameOver(function(){window.autoplay&&
(removeAllWinBorders(),rewriteStaticMatrix(),a&&a())});window.autoplay||a&&a()}():r()||requestAnimationFrame(function(){r()||m((new Date).getTime())})};isSoundEnabled()&&isMusicEnabled()&&playSoundById("reel-run-sound");window.reelsRunned=!0;m(h-1E3/30)}}}function forceReelsStop(){window.reelsRunned=!1;window.stopLinesAnimation=!0;for(var a=0,b=0;a<window.reelsDist.length;++a)window.reelsDist[a]=0>=window.reelsDist[a]?window.reelsDist[a]:++b}
function getMatrix(){for(var a=$(".reel").length,b=_.map(_.range(a),function(){return[]}),c=0;c<a;++c)for(var e=reels[c],h=0;h<e.length;++h){var m=e[h],l=m.y;(l>0*window.symbolHeight-20&&l<0*window.symbolHeight+20||l>1*window.symbolHeight-20&&l<1*window.symbolHeight+20||l>2*window.symbolHeight-20&&l<2*window.symbolHeight+20)&&b[c].push(m)}return b}
function getMatrixLines(){for(var a=parseInt($("#linesCountField").text()),b=getMatrix(),c=window.gameConfig.getMatrixIndeces(),e=[],h=0;h<c.length&&h<a;++h){for(var m=c[h],l=[],n=0;n<m.length;++n)l.push(b[n][m[n]]);e.push(l)}return e}function getMatrixHorizontalLines(){for(var a=getMatrix(),b=[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2]],c=[],e=0;e<b.length&&3>e;++e){for(var h=b[e],m=[],l=0;l<h.length;++l)m.push(a[l][h[l]]);c.push(m)}return c}
function getScatters(){for(var a=getMatrix(),b=[],c=0;c<a.length&&5>b.length;++c)for(var e=0;e<a[c].length&&5>b.length;++e){var h=a[c][e];window.gameConfig.isScatter(h.symbol)&&(h.xpos=c,b.push(h))}return b.length&&window.gameConfig.getWinMatrix()[b[0].symbol][b.length]?b:!1}function getMatrixLineFruit(a){return window.gameConfig.getMatrixLineFruit?window.gameConfig.getMatrixLineFruit(a):getMatrixLineFruitDefault(a)}
function getMatrixLineFruitDefault(a){for(var b=window.gameConfig.getWinMatrix(),c=!1,e=[],h=0;h<a.length;++h){var m=a[h],l=m.symbol;if(c)if(window.gameConfig.isSubstitute(l))e.push(m);else if(window.gameConfig.isScatter(l))break;else if(c!=l)break;else e.push(m);else if(window.gameConfig.isSubstitute(l))e.push(m);else if(window.gameConfig.isScatter(l))break;else e.push(m),c=l}return c&&b[c][e.length]?e:!1}function getCredit(){return parseInt($("#creditField").text())}
function generatePresetSymbols(a){var b={};_.each(a,function(a){for(var e=-1,h=0;26>h;++h)if("abcdefghijklmnopqrstuvwxyz"[h]==a){e=h;break}0<=e&&(b[a+a]=e)});return b}function showUserBalance(){$.get("/balance.php",function(a){$("#footer-credit > h1").text(a);$("#footer-credit > h2").text((a/100).formatMoney(2,".",","));$("#creditField").text(a)})}function updateBalance(a){$.post("/setbalance.php?money="+a,function(){showUserBalance()})}
function getNewSpin(a){$.post("/common/php/getnewspin.php?gameid="+window.gameId,function(b){if("false"==b)a&&a(!1);else{b=JSON.parse(b);window.reelsDist=Array($(".reel").length);for(var c=0;c<b.spin.length;++c)window.reelsDist[c]=b.spin[c];b.id&&b.guid?a&&a(b):a&&a(!1)}})}function setNewSpin(a){getNewSpin(function(b){if(b){var c=b.id;window.newspin=parseInt(c);for(var e=b.guid,c=c+"";6>c.length;)c="0"+c;c="#"+c;$("#top-menu-spin-id").text(c);window.spintoken=e;a(b)}else a&&a(!1)})};
