var $jscomp={scope:{},findInternal:function(a,d,b){a instanceof String&&(a=String(a));for(var e=a.length,c=0;c<e;c++){var f=a[c];if(d.call(b,f,c,a))return{i:c,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,d,b,e){if(d){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in b||(b[c]={});b=b[c]}a=a[a.length-1];e=b[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");var gambleRandomAnimationTimeout=50,translateAnimationTimeout=20;function genGambleCards(){var a=$("#gamble-cards");_.each(a.find(".card"),function(a){a=$(a);a.css("background-image","url("+window.data.imgs["card-"+Math.floor(4*Math.random())].src+")")})}
function gambleRandomAnimation(){if(window.inGambleAnimation){var a=document.getElementById("big-card");$(a).attr("width",$(a).css("width"));$(a).attr("height",$(a).css("height"));var d=a.getContext("2d");window.gambleCard=(new Date).getMilliseconds()%2?"card-red":"card-blue";d.clearRect(0,0,a.width,a.height);d.drawImage(data.imgs[window.gambleCard],0,0,211,298);(playSoundById("gamblesuspense")||{loop:!1}).loop=!0;setTimeout(gambleRandomAnimation,gambleRandomAnimationTimeout)}else stopSoundById("gamblesuspense")}
function testGambleWin(a){window.inGambleAnimation=!1;var d=window.gambleCard==a;a=document.getElementById("big-card");$(a).attr("width",$(a).css("width"));$(a).attr("height",$(a).css("height"));var b=a.getContext("2d");b.clearRect(0,0,a.width,a.height);b.drawImage(data.imgs[window.gambleCard],0,0,211,298);var e;"card-red"==window.gambleCard?e=randomInteger(0,2)?"card-0":"card-3":"card-blue"==window.gambleCard&&(e=randomInteger(0,2)?"card-1":"card-2");window.gambleCard=!1;$("#big-card-front").css("background-image",
"url("+window.data.imgs[e].src+")");var c=0,f,m,n,p,q,r,t,u,k=function(a,b){c+=5;a.css("left",a.offset().left+5*q+"px").css("top",a.offset().top+5*r+"px").css("width",a.width()+5*t+"px").css("height",a.height()+5*u+"px");$(_.last($(".card"))).css("opacity",1-c/100);$(_.first($(".card"))).css("margin-left",10+c/100*70+"px");if(100<=c){var d=$(document.createElement("div")).addClass("card").css("background-image",a.css("background-image"));$("#gamble-cards").prepend(d);$($(".card")[1]).css("margin-left",
"10px");a.remove();$("#big-card").css("transform","rotateY(0deg)");$("#big-card-front").css("transform","rotateY(180deg)");for($("#big-card-outer").show();6<=$(".card").length;)$(_.last($(".card"))).remove();b&&b()}else(function(a,b){setTimeout(function(){window.requestAnimationFrame?function(a,b){requestAnimationFrame(function(){k(a,b)})}(a,b):k(a,b)},translateAnimationTimeout)})(a,b)},g=0,h=!1,l=function(a){g+=h?-5:5;$("#big-card").css("transform","rotateY("+g+"deg)");$("#big-card-front").css("transform",
"rotateY("+(180+g)+"deg)");var b=$("#big-card-front");if(h?0>=g:180<=g)if(d){b=$(document.createElement("div")).css("position","absolute").css("left",b.offset().left+"px").css("top",b.offset().top+"px").css("width",b.width()+"px").css("height",b.height()+"px").css("background-image",b.css("background-image")).css("background-size","contain").css("background-repeat","no-repeat");$("body").append(b);$("#big-card-outer").hide();var c=$($(".card")[0]);f=c.offset().left;m=c.offset().top;n=c.width();p=
c.height();q=(f-b.offset().left)/100;r=(m-b.offset().top)/100;t=(n-b.width())/100;u=(p-b.height())/100;k(b,a)}else h?(h=!1,$("#big-card-outer").show(),a&&a()):(h=!0,l(a));else setTimeout(function(){l(a)},20)};l(function(){d?(playSoundById("gamble-win"),window.totalWin=parseInt($("#gamble-double-money").text()),$("#label-info > span").text(window.totalWin+" won"),$("#gamble-current-money").text(window.totalWin),$("#gamble-double-money").text(2*window.totalWin),window.inGambleAnimation=!0,window.inGambleState=
!0,gambleRandomAnimation()):($("#label-info > span").text("0 won"),window.totalWin=0,window.inGambleState=!1,window.needCollect=!1,$("#button-start").text("Start"),setTimeout(hideGamble,1E3))})}function redGambleClick(){window.inGambleState&&window.inGambleAnimation&&testGambleWin("card-red")}function blackGambleClick(){window.inGambleState&&window.inGambleAnimation&&testGambleWin("card-blue")}
function openGamble(){window.needCollect&&($("#button-start").css("background-position","0 -222px"),$("#button-start").text("Collect"),$("#button-gamble").style("background-position","0 0","important"),$("#button-autoplay").style("background-position","0 0","important"),$("#button-paytable").style("background-position","0 0","important"),window.inGambleState=calculateWin(),$("#gamble-current-money").text(window.inGambleState),$("#gamble-double-money").text(2*window.inGambleState),genGambleCards(),
$("#gamble-content").slideDown("fast"),window.inGambleAnimation=!0,gambleRandomAnimation())}function hideGamble(){window.inGambleState=!1;$("#gamble-content").slideUp("fast");$("#button-autoplay").style("background-position","0 -222px","nonimportant");$("#button-paytable").style("background-position","0 -222px","nonimportant");$("#button-start").style("background-position","0 -222px","nonimportant");$("#button-start").text("Start");$("#button-autoplay").text("Autoplay")};
