var data;window.cacheVersion=10133344;window.enablePreloaderLog=!0;window.showDebugText=!1;function unload(b){for(var t in data.sounds)data.sounds[t].unload();b&&b()}function supportsLocalStorage(){return!1}
function preloader(b,t){var k=function(a){a.preventDefault()},x=function(){var a=[];("undefined"!==typeof b.loadSymbolsAnimations&&!0===b.loadSymbolsAnimations||"undefined"===typeof b.loadSymbolsAnimations)&&b.symbols&&_.each(b.symbols,function(c){a.push(c)});b.animations&&(a=a.concat(b.animations));return a};document.getElementById("preloader-background").addEventListener("gesturechange",k,!1);document.getElementById("preloader-outer").addEventListener("gesturechange",k,!1);document.getElementById("preloader").addEventListener("gesturechange",
k,!1);localforage.config({driver:localforage.INDEXEDDB,name:"valvemovie"});if(supportsLocalStorage())if(k=localStorage[b.name+":version"],void 0===k)try{localStorage[b.name+":version"]=window.cacheVersion,window.saveResourcesToCache=!0,window.loadResourcesFromCache=!1}catch(a){window.saveResourcesToCache=!1,window.loadResourcesFromCache=!1}else if(parseInt(k)!=window.cacheVersion)try{localStorage[b.name+":version"]=window.cacheVersion,window.saveResourcesToCache=!0,window.loadResourcesFromCache=!1}catch(a){window.saveResourcesToCache=
!1,window.loadResourcesFromCache=!1}else window.saveResourcesToCache=!1,window.loadResourcesFromCache=!0;else window.saveResourcesToCache=!1,window.loadResourcesFromCache=!1;k=$("#preloader");k.attr("width","800");k.attr("height","800");var f=k[0].getContext("2d"),y={},z={},A={},n={},C={},u={},D={},E={},g=0,d=0,p=0,q=0,m=0,l=0,H=b.imgtype?b.imgtype:"jpg",v=function(){return b.symbolsModifications?[""].concat(b.symbolsModifications):["","_b"]},k=(b.symbols?b.symbols.length:0)*v().length,I=4*x().length,
J=b.sounds?b.sounds.length*(isMobile()?1:2):0,K=k+I+J,e=function(a){applyScale();f.fillStyle="black";f.fillRect(0,0,800,800);var c=Math.ceil(100*l/K);isMobile()&&(c=Math.ceil(c/120*100));100<c&&(c=100);var b=c+" %";f.font="bold 48px Courier";var e=f.measureText(b);f.fillStyle="white";f.fillText(b,400-e.width/2,376);f.strokeStyle="white";f.lineWidth=8;for(b=0;360>b&&!(b>=360*c/100);b+=10)e=b/180*3.1415,f.moveTo(400+250*Math.cos(e),400+250*Math.sin(e)-24),f.lineTo(400+300*Math.cos(e),400+300*Math.sin(e)-
24),f.stroke();window.showDebugText&&a&&(f.font="bold 40px Courier",f.fillStyle="white",c=f.measureText(a),f.fillText(a,400-c.width/2,740));window.enablePreloaderLog&&console.log(a)},F=function(a,c){q||e("Loading images...");if(q>=(a?a.length:0))c&&c();else{var L=a[q][0],d="/games/"+b.game+"/imgs/"+a[q][1],h=new Image;window.enablePreloaderLog&&console.log("Preload image: "+d);(function(a,c,b,d){a.addEventListener("load",function(){E[c]=a;++q;++l;e('Image "'+c+'" loaded');setTimeout(function(){F(b,
d)},1)},!1)})(h,L,a,c);h.src=d}},B=function(a,c,b){d||e("Calculating animation length...");if(d>=(a?a.length:0))$(".jsgif").remove(),$(".tagtoremove").remove(),b&&b();else{var g=a[d];c&&a.unshift();c&&!n[a[d]]?(u[a[d]]=!1,++l,e('Length of "'+a[d]+'-red" undefined'),++d,setTimeout(function(){B(a,!c,b)},1)):(new Image,$.get("/common/php/getgiflen.php?game="+window.gameConfig.preloaderSettings.game+"&file="+(g+(c?"-red":"")+".gif"),function(h){"false"==h.trim()?c?(u[a[d]]=!1,++l,e("Can't load \""+a[d]+
'-red" animation'),++d):(++l,a[d]=!1,e("Can't load \""+a[d]+'" animation')):(h=parseInt(h),c?(u[a[d]]=h,++l,e('Length of "'+a[d]+'-red" loaded from DB'),++d):(C[a[d]]=h,++l,e('Length of "'+a[d]+'" loaded from DB')));setTimeout(function(){B(a,!c,b)},1)}))}},w=function(a,c,d){p||v().length!=c.length||e("Loading symbols...");if(p>=(a?a.length:0))d&&d();else if(c&&c.length){var g=window.gameConfig.symbols[p],h=c.shift(),f="/games/"+b.game+"/imgs/symbols/"+g+h+"."+H,k=new Image;(function(b){window.enablePreloaderLog&&
console.log("Preload symbol: "+f);k=new Image;(function(a,b,c,d,g,h){a.addEventListener("load",function(){y[b+d]=a;var f=new PIXI.BaseTexture(a),f=new PIXI.Texture(f);z[b+d]=f;++l;e('Symbol "'+b+d+'" loaded');setTimeout(function(){c&&c.length||++p;w(g,c,h)},1)});a.addEventListener("error",function(){y[b+d]=!1;z[b+d]=!1;++l;e('Symbol "'+b+d+'" not loaded');setTimeout(function(){c&&c.length||++p;w(g,c,h)},1)})})(k,g,c,h,a,b);k.src=f})(d)}else c=v(),setTimeout(function(){w(a,c,d)},1)},r=function(a,c,
d){g||e("Loading symbols...");if(g>=(a?a.length:0))d&&d();else{var f="/games/"+b.game+"/imgs/symbols/"+a[g]+(c?"-red":"")+".gif",h=new Image,k=b.name+":"+f,m=function(){window.enablePreloaderLog&&console.log("Preload "+(c?"red ":"")+"animation: "+f);(function(a,b,c,d){a.addEventListener("load",function(){b?(n[c[g]]=a,++l,e('Animation "'+c[g]+'" loaded'),++g):(A[c[g]]=a,++l,e('Animation "'+c[g]+'-red" loaded'));if(window.saveResourcesToCache){var h=new XMLHttpRequest;h.responseType="blob";h.onload=
function(){var a=new FileReader;(function(a){a.onloadend=function(){var e=a.result.replace(/^data:image\/(gif);base64,/,"");localforage.setItem(k,LZString.compressToUTF16(e),function(a,e){a?console.log(a):success=!0;setTimeout(function(){r(c,!b,d)},1)})}})(a);a.readAsDataURL(h.response)};h.open("GET",f);h.send()}else setTimeout(function(){r(c,!b,d)},1)},!1);b&&a.addEventListener("error",function(){n[c[g]]=!1;++l;e("Can't load \""+c[g]+'-red" animation');++g;setTimeout(function(){r(c,!b,d)},1)},!1)})(h,
c,a,d);h.src=f};window.saveResourcesToCache?m():window.loadResourcesFromCache?(window.enablePreloaderLog&&console.log("Preload "+(c?"red ":"")+"animation"+(window.loadResourcesFromCache?" [from cache]":"")+": "+f),localforage.getItem(k,function(b,f){b&&console.log(b);null==f?m():(function(a,b,c,d){a.addEventListener("load",function(){b?(n[c[g]]=a,++l,e('Animation "'+c[g]+'-red" loaded')):(A[c[g]]=a,++l,e('Animation "'+c[g]+'" loaded'));b&&++g;setTimeout(function(){r(c,!b,d)},1)},!1);a.addEventListener("error",
function(){m()},!1)}(h,c,a,d),h.src="data:image/gif;base64,"+LZString.decompressFromUTF16(f))})):m()}},G=function(a,c){m||e("Loading sounds...");if(m>=(a?a.length:0))c&&c();else{var d=a[m][0],f=a[m][1],h="undefined"!==typeof a[m][2]&&a[m][2],g=(h?"/common":"/games/"+b.game)+"/sounds/"+f+".ogg",k=(h?"/common":"/games/"+b.game)+"/sounds/"+f+".mp3",n=(h?"/common":"/games/"+b.game)+"/sounds/"+f+".m4a",p=isAndroid()||isChrome()||isOpera()?g:isiOS()||isSafari()?n:[g,k];(function(b){var d=new Howl({src:p,
onload:function(){isAndroid()||isChrome()||isOpera()?(l+=1,e('Sound "'+g+'" loaded')):isiOS()||isSafari()?(l+=1,e('Sound "'+n+'" loaded')):(l+=1,e('Sound "'+g+'" loaded'),l+=1,e('Sound "'+k+'" loaded'));++m;D[b]=d;setTimeout(function(){G(a,c)},1)}})})(d)}};e("Start loading...");if(window.enablePreloaderLog){var M=(new Date).getTime();e("Preloading started")}w(b.symbols,v(),function(){F(b.imgs,function(){r(x(),!1,function(){B(x(),!1,function(){G(b.sounds,function(){$("#preloader-background").hide();
isMobile()?tryShowRotationBlock(function(){$("#body-repeat").show()}):$("#body-repeat").show();e("Preloading completed");if(window.enablePreloaderLog){var a=(new Date).getTime();e("Total time: "+(a-M))}data={symbols:y,"pixi-symbols":z,sounds:D,animations:A,"animations-length":C,"animations-red":n,"animations-red-length":u,imgs:E};t&&t(data)})})})})})};
